# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ==============================================================================
# CODE GENERATED BY @a2ui/cli. DO NOT EDIT DIRECTLY.
#
# Catalog ID: https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json
#
# This file was automatically generated by the A2UI CLI code generator.
# Any manual modifications will be lost upon regeneration.
# ==============================================================================
"""Type-safe A2UI builders for basic (version v0.9.1).

AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
Generated by @a2ui/cli.
"""

__a2ui_codegen__ = "@a2ui/cli"

from typing import Annotated, Any, Literal, Optional, Sequence
from pydantic import BaseModel, ConfigDict, Field

from a2ui.builder.v0_9 import (
    AccessibilityAttributes,
    Action,
    ActionEvent,
    CheckRule,
    Child,
    ChildList,
    ComponentBuilderNode,
    ComponentRef,
    ComponentTree,
    DataBinding,
    DynamicChildList,
    FunctionCall,
    IdAllocator,
    OPEN_ENUM,
    bind,
    create_surface,
    event,
    flatten_component_tree,
    update_components,
)


# =============================================================================
# Types & Enums
# =============================================================================
#
# Catalog enums carry OPEN_ENUM metadata: the annotation stays the strict Literal
# for authoring and type checking, and unknown values are only accepted when
# parsing with a lenient validation context.

TextVariant = Annotated[
    Literal["h1", "h2", "h3", "h4", "h5", "caption", "body"], OPEN_ENUM
]
ImageFit = Annotated[
    Literal["contain", "cover", "fill", "none", "scaleDown"], OPEN_ENUM
]
ImageVariant = Annotated[
    Literal[
        "icon", "avatar", "smallFeature", "mediumFeature", "largeFeature", "header",
    ],
    OPEN_ENUM,
]
IconName = Annotated[
    Literal[
        "accountCircle", "add", "arrowBack", "arrowForward", "attachFile",
        "calendarToday", "call", "camera", "check", "close", "delete", "download",
        "edit", "event", "error", "fastForward", "favorite", "favoriteOff", "folder",
        "help", "home", "info", "locationOn", "lock", "lockOpen", "mail", "menu",
        "moreVert", "moreHoriz", "notificationsOff", "notifications", "pause",
        "payment", "person", "phone", "photo", "play", "print", "refresh", "rewind",
        "search", "send", "settings", "share", "shoppingCart", "skipNext",
        "skipPrevious", "star", "starHalf", "starOff", "stop", "upload", "visibility",
        "visibilityOff", "volumeDown", "volumeMute", "volumeOff", "volumeUp", "warning",
    ],
    OPEN_ENUM,
]
FlexJustify = Annotated[
    Literal[
        "start", "center", "end", "spaceBetween", "spaceAround", "spaceEvenly",
        "stretch",
    ],
    OPEN_ENUM,
]
FlexAlign = Annotated[Literal["center", "end", "start", "stretch"], OPEN_ENUM]
ListDirection = Annotated[Literal["vertical", "horizontal"], OPEN_ENUM]
ListAlign = Annotated[Literal["start", "center", "end", "stretch"], OPEN_ENUM]
DividerAxis = Annotated[Literal["horizontal", "vertical"], OPEN_ENUM]
ButtonVariant = Annotated[Literal["default", "primary", "borderless"], OPEN_ENUM]
TextFieldVariant = Annotated[
    Literal["longText", "number", "shortText", "obscured"], OPEN_ENUM
]
ChoicePickerVariant = Annotated[
    Literal["multipleSelection", "mutuallyExclusive"], OPEN_ENUM
]
ChoicePickerDisplayStyle = Annotated[Literal["checkbox", "chips"], OPEN_ENUM]


# =============================================================================
# Item Models
# =============================================================================


class IconNameSvgPath(BaseModel):
    r"""IconNameSvgPath item model."""

    model_config = ConfigDict(
        extra="forbid",
        arbitrary_types_allowed=False,
        validate_by_name=True,
    )

    svg_path: str = Field(serialization_alias="svgPath")


class TabItem(BaseModel):
    r"""An array of objects, where each object defines a tab with a title and a child component."""

    model_config = ConfigDict(
        extra="forbid",
        arbitrary_types_allowed=False,
        validate_by_name=True,
    )

    title: str | DataBinding | FunctionCall
    child: Child


class ChoicePickerOption(BaseModel):
    r"""The list of available options to choose from."""

    model_config = ConfigDict(
        extra="forbid",
        arbitrary_types_allowed=False,
        validate_by_name=True,
    )

    label: str | DataBinding | FunctionCall
    value: str


# =============================================================================
# Components
# =============================================================================


class Text(ComponentBuilderNode):
    r"""Text component."""

    component: Literal["Text"] = "Text"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    text: str | DataBinding | FunctionCall
    variant: Optional[TextVariant] = "body"


class Image(ComponentBuilderNode):
    r"""Image component."""

    component: Literal["Image"] = "Image"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None
    fit: Optional[ImageFit] = "fill"
    variant: Optional[ImageVariant] = "mediumFeature"


class Icon(ComponentBuilderNode):
    r"""Icon component."""

    component: Literal["Icon"] = "Icon"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    name: IconName | IconNameSvgPath | DataBinding | FunctionCall


class Video(ComponentBuilderNode):
    r"""Video component."""

    component: Literal["Video"] = "Video"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall


class AudioPlayer(ComponentBuilderNode):
    r"""AudioPlayer component."""

    component: Literal["AudioPlayer"] = "AudioPlayer"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None


class Row(ComponentBuilderNode):
    r"""A layout component that arranges its children horizontally. To create a grid layout, nest Columns within this Row."""

    component: Literal["Row"] = "Row"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    children: ChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"


class Column(ComponentBuilderNode):
    r"""A layout component that arranges its children vertically. To create a grid layout, nest Rows within this Column."""

    component: Literal["Column"] = "Column"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    children: ChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"


class List(ComponentBuilderNode):
    r"""List component."""

    component: Literal["List"] = "List"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    children: ChildList
    direction: Optional[ListDirection] = "vertical"
    align: Optional[ListAlign] = "stretch"


class Card(ComponentBuilderNode):
    r"""Card component."""

    component: Literal["Card"] = "Card"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    child: Child


class Tabs(ComponentBuilderNode):
    r"""Tabs component."""

    component: Literal["Tabs"] = "Tabs"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    tabs: Sequence[TabItem]


class Modal(ComponentBuilderNode):
    r"""Modal component."""

    component: Literal["Modal"] = "Modal"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    trigger: Child
    content: Child


class Divider(ComponentBuilderNode):
    r"""Divider component."""

    component: Literal["Divider"] = "Divider"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    axis: Optional[DividerAxis] = "horizontal"


class Button(ComponentBuilderNode):
    r"""Button component."""

    component: Literal["Button"] = "Button"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    checks: Optional[Sequence[CheckRule]] = None
    child: Child
    variant: Optional[ButtonVariant] = "default"
    action: Action


class TextField(ComponentBuilderNode):
    r"""TextField component."""

    component: Literal["TextField"] = "TextField"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    checks: Optional[Sequence[CheckRule]] = None
    label: str | DataBinding | FunctionCall
    value: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[TextFieldVariant] = "shortText"
    validation_regexp: Optional[str] = Field(
        default=None, serialization_alias="validationRegexp"
    )


class CheckBox(ComponentBuilderNode):
    r"""CheckBox component."""

    component: Literal["CheckBox"] = "CheckBox"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    checks: Optional[Sequence[CheckRule]] = None
    label: str | DataBinding | FunctionCall
    value: bool | DataBinding | FunctionCall


class ChoicePicker(ComponentBuilderNode):
    r"""A component that allows selecting one or more options from a list."""

    component: Literal["ChoicePicker"] = "ChoicePicker"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    checks: Optional[Sequence[CheckRule]] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[ChoicePickerVariant] = "mutuallyExclusive"
    options: Sequence[ChoicePickerOption]
    value: Sequence[str] | DataBinding | FunctionCall
    display_style: Optional[ChoicePickerDisplayStyle] = Field(
        default="checkbox", serialization_alias="displayStyle"
    )
    filterable: Optional[bool] = False


class Slider(ComponentBuilderNode):
    r"""Slider component."""

    component: Literal["Slider"] = "Slider"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    checks: Optional[Sequence[CheckRule]] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    min: Optional[float] = 0
    max: float
    value: float | DataBinding | FunctionCall


class DateTimeInput(ComponentBuilderNode):
    r"""DateTimeInput component."""

    component: Literal["DateTimeInput"] = "DateTimeInput"
    accessibility: Optional[AccessibilityAttributes] = None
    weight: Optional[float] = None
    checks: Optional[Sequence[CheckRule]] = None
    value: str | DataBinding | FunctionCall
    enable_date: Optional[bool] = Field(default=False, serialization_alias="enableDate")
    enable_time: Optional[bool] = Field(default=False, serialization_alias="enableTime")
    min: Optional[Any] = None
    max: Optional[Any] = None
    label: Optional[str | DataBinding | FunctionCall] = None


# =============================================================================
# Functions & Function Classes
# =============================================================================


class Required(FunctionCall):
    r"""Checks that the value is not null, undefined, or empty."""

    def __init__(self, *, value: Any, **kwargs: Any):
        super().__init__(call="required", args={"value": value}, **kwargs)


def required(*, value: Any) -> Required:
    r"""Checks that the value is not null, undefined, or empty."""
    return Required(value=value)


class Regex(FunctionCall):
    r"""Checks that the value matches a regular expression string."""

    def __init__(
        self,
        *,
        value: str | DataBinding | FunctionCall,
        pattern: str,
        **kwargs: Any,
    ):
        super().__init__(
            call="regex",
            args={"value": value, "pattern": pattern},
            **kwargs,
        )


def regex(*, value: str | DataBinding | FunctionCall, pattern: str) -> Regex:
    r"""Checks that the value matches a regular expression string."""
    return Regex(value=value, pattern=pattern)


class Length(FunctionCall):
    r"""Checks string length constraints."""

    def __init__(
        self,
        *,
        value: str | DataBinding | FunctionCall,
        min: Optional[float] = None,
        max: Optional[float] = None,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value}
        if min is not None:
            args["min"] = min
        if max is not None:
            args["max"] = max
        super().__init__(call="length", args=args, **kwargs)


def length(
    *,
    value: str | DataBinding | FunctionCall,
    min: Optional[float] = None,
    max: Optional[float] = None,
) -> Length:
    r"""Checks string length constraints."""
    return Length(value=value, min=min, max=max)


class Numeric(FunctionCall):
    r"""Checks numeric range constraints."""

    def __init__(
        self,
        *,
        value: float | DataBinding | FunctionCall,
        min: Optional[float] = None,
        max: Optional[float] = None,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value}
        if min is not None:
            args["min"] = min
        if max is not None:
            args["max"] = max
        super().__init__(call="numeric", args=args, **kwargs)


def numeric(
    *,
    value: float | DataBinding | FunctionCall,
    min: Optional[float] = None,
    max: Optional[float] = None,
) -> Numeric:
    r"""Checks numeric range constraints."""
    return Numeric(value=value, min=min, max=max)


class Email(FunctionCall):
    r"""Checks that the value is a valid email address."""

    def __init__(self, *, value: str | DataBinding | FunctionCall, **kwargs: Any):
        super().__init__(call="email", args={"value": value}, **kwargs)


def email(*, value: str | DataBinding | FunctionCall) -> Email:
    r"""Checks that the value is a valid email address."""
    return Email(value=value)


class FormatString(FunctionCall):
    """Performs string interpolation of data model values and other functions in the catalog functions list and returns the resulting string. The value string can contain interpolated expressions in the `${expression}` format. Supported expression types include: JSON Pointer paths to the data model (e.g., `${/absolute/path}` or `${relative/path}`), and client-side function calls (e.g., `${now()}`). Function arguments must be named (e.g., `${formatDate(value:${/currentDate}, format:'MM-dd')}`). To include a literal `${` sequence, escape it as `\\${`."""

    def __init__(self, *, value: str | DataBinding | FunctionCall, **kwargs: Any):
        super().__init__(call="formatString", args={"value": value}, **kwargs)


def format_string(*, value: str | DataBinding | FunctionCall) -> FormatString:
    """Performs string interpolation of data model values and other functions in the catalog functions list and returns the resulting string. The value string can contain interpolated expressions in the `${expression}` format. Supported expression types include: JSON Pointer paths to the data model (e.g., `${/absolute/path}` or `${relative/path}`), and client-side function calls (e.g., `${now()}`). Function arguments must be named (e.g., `${formatDate(value:${/currentDate}, format:'MM-dd')}`). To include a literal `${` sequence, escape it as `\\${`."""
    return FormatString(value=value)


class FormatNumber(FunctionCall):
    r"""Formats a number with the specified grouping and decimal precision."""

    def __init__(
        self,
        *,
        value: float | DataBinding | FunctionCall,
        decimals: Optional[float | DataBinding | FunctionCall] = None,
        grouping: Optional[bool | DataBinding | FunctionCall] = None,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value}
        if decimals is not None:
            args["decimals"] = decimals
        if grouping is not None:
            args["grouping"] = grouping
        super().__init__(call="formatNumber", args=args, **kwargs)


def format_number(
    *,
    value: float | DataBinding | FunctionCall,
    decimals: Optional[float | DataBinding | FunctionCall] = None,
    grouping: Optional[bool | DataBinding | FunctionCall] = None,
) -> FormatNumber:
    r"""Formats a number with the specified grouping and decimal precision."""
    return FormatNumber(value=value, decimals=decimals, grouping=grouping)


class FormatCurrency(FunctionCall):
    r"""Formats a number as a currency string."""

    def __init__(
        self,
        *,
        value: float | DataBinding | FunctionCall,
        currency: str | DataBinding | FunctionCall,
        decimals: Optional[float | DataBinding | FunctionCall] = None,
        grouping: Optional[bool | DataBinding | FunctionCall] = None,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value, "currency": currency}
        if decimals is not None:
            args["decimals"] = decimals
        if grouping is not None:
            args["grouping"] = grouping
        super().__init__(call="formatCurrency", args=args, **kwargs)


def format_currency(
    *,
    value: float | DataBinding | FunctionCall,
    currency: str | DataBinding | FunctionCall,
    decimals: Optional[float | DataBinding | FunctionCall] = None,
    grouping: Optional[bool | DataBinding | FunctionCall] = None,
) -> FormatCurrency:
    r"""Formats a number as a currency string."""
    return FormatCurrency(
        value=value,
        currency=currency,
        decimals=decimals,
        grouping=grouping,
    )


class FormatDate(FunctionCall):
    r"""Formats a timestamp into a string using a pattern."""

    def __init__(
        self,
        *,
        value: Any | DataBinding | FunctionCall,
        format: str | DataBinding | FunctionCall,
        **kwargs: Any,
    ):
        super().__init__(
            call="formatDate",
            args={"value": value, "format": format},
            **kwargs,
        )


def format_date(
    *,
    value: Any | DataBinding | FunctionCall,
    format: str | DataBinding | FunctionCall,
) -> FormatDate:
    r"""Formats a timestamp into a string using a pattern."""
    return FormatDate(value=value, format=format)


class Pluralize(FunctionCall):
    r"""Returns a localized string based on the Common Locale Data Repository (CLDR) plural category of the count (zero, one, two, few, many, other). Requires an 'other' fallback. For English, just use 'one' and 'other'."""

    def __init__(
        self,
        *,
        value: float | DataBinding | FunctionCall,
        zero: Optional[str | DataBinding | FunctionCall] = None,
        one: Optional[str | DataBinding | FunctionCall] = None,
        two: Optional[str | DataBinding | FunctionCall] = None,
        few: Optional[str | DataBinding | FunctionCall] = None,
        many: Optional[str | DataBinding | FunctionCall] = None,
        other: str | DataBinding | FunctionCall,
        **kwargs: Any,
    ):
        args: dict[str, Any] = {"value": value, "other": other}
        if zero is not None:
            args["zero"] = zero
        if one is not None:
            args["one"] = one
        if two is not None:
            args["two"] = two
        if few is not None:
            args["few"] = few
        if many is not None:
            args["many"] = many
        super().__init__(call="pluralize", args=args, **kwargs)


def pluralize(
    *,
    value: float | DataBinding | FunctionCall,
    zero: Optional[str | DataBinding | FunctionCall] = None,
    one: Optional[str | DataBinding | FunctionCall] = None,
    two: Optional[str | DataBinding | FunctionCall] = None,
    few: Optional[str | DataBinding | FunctionCall] = None,
    many: Optional[str | DataBinding | FunctionCall] = None,
    other: str | DataBinding | FunctionCall,
) -> Pluralize:
    r"""Returns a localized string based on the Common Locale Data Repository (CLDR) plural category of the count (zero, one, two, few, many, other). Requires an 'other' fallback. For English, just use 'one' and 'other'."""
    return Pluralize(
        value=value,
        zero=zero,
        one=one,
        two=two,
        few=few,
        many=many,
        other=other,
    )


class OpenUrl(FunctionCall):
    r"""Opens the specified URL in a browser or handler. This function has no return value."""

    def __init__(self, *, url: str, **kwargs: Any):
        super().__init__(call="openUrl", args={"url": url}, **kwargs)


def open_url(*, url: str) -> OpenUrl:
    r"""Opens the specified URL in a browser or handler. This function has no return value."""
    return OpenUrl(url=url)


class And(FunctionCall):
    r"""Performs a logical AND operation on a list of boolean values."""

    def __init__(
        self,
        *,
        values: Sequence[bool | DataBinding | FunctionCall],
        **kwargs: Any,
    ):
        super().__init__(call="and", args={"values": values}, **kwargs)


def and_(*, values: Sequence[bool | DataBinding | FunctionCall]) -> And:
    r"""Performs a logical AND operation on a list of boolean values."""
    return And(values=values)


class Or(FunctionCall):
    r"""Performs a logical OR operation on a list of boolean values."""

    def __init__(
        self,
        *,
        values: Sequence[bool | DataBinding | FunctionCall],
        **kwargs: Any,
    ):
        super().__init__(call="or", args={"values": values}, **kwargs)


def or_(*, values: Sequence[bool | DataBinding | FunctionCall]) -> Or:
    r"""Performs a logical OR operation on a list of boolean values."""
    return Or(values=values)


class Not(FunctionCall):
    r"""Performs a logical NOT operation on a boolean value."""

    def __init__(self, *, value: bool | DataBinding | FunctionCall, **kwargs: Any):
        super().__init__(call="not", args={"value": value}, **kwargs)


def not_(*, value: bool | DataBinding | FunctionCall) -> Not:
    r"""Performs a logical NOT operation on a boolean value."""
    return Not(value=value)


# =============================================================================
# Exports
# =============================================================================

__all__ = [
    "TextVariant",
    "ImageFit",
    "ImageVariant",
    "IconName",
    "FlexJustify",
    "FlexAlign",
    "ListDirection",
    "ListAlign",
    "DividerAxis",
    "ButtonVariant",
    "TextFieldVariant",
    "ChoicePickerVariant",
    "ChoicePickerDisplayStyle",
    "IconNameSvgPath",
    "TabItem",
    "ChoicePickerOption",
    "Text",
    "Image",
    "Icon",
    "Video",
    "AudioPlayer",
    "Row",
    "Column",
    "List",
    "Card",
    "Tabs",
    "Modal",
    "Divider",
    "Button",
    "TextField",
    "CheckBox",
    "ChoicePicker",
    "Slider",
    "DateTimeInput",
    "Required",
    "Regex",
    "Length",
    "Numeric",
    "Email",
    "FormatString",
    "FormatNumber",
    "FormatCurrency",
    "FormatDate",
    "Pluralize",
    "OpenUrl",
    "And",
    "Or",
    "Not",
    "required",
    "regex",
    "length",
    "numeric",
    "email",
    "format_string",
    "format_number",
    "format_currency",
    "format_date",
    "pluralize",
    "open_url",
    "and_",
    "or_",
    "not_",
    "AccessibilityAttributes",
    "Action",
    "ActionEvent",
    "CheckRule",
    "Child",
    "ChildList",
    "ComponentBuilderNode",
    "ComponentRef",
    "ComponentTree",
    "DataBinding",
    "DynamicChildList",
    "FunctionCall",
    "IdAllocator",
    "bind",
    "create_surface",
    "event",
    "flatten_component_tree",
    "update_components",
]
