// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'dart:io';
import 'package:path/path.dart' as p;
import '../../analyzer/types.dart';
import 'type_mapper.dart';

const licenseHeader = '''# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
''';

String extractCatalogName(String catalogId) {
  final parts = catalogId.split('/').where((s) => s.isNotEmpty).toList();
  var last = parts.isNotEmpty ? parts.last : 'catalog';
  last = last.replaceAll(RegExp(r'\.json$'), '');
  if (last == 'catalog' && parts.length > 1) {
    final prev = parts[parts.length - 2].replaceAll(RegExp(r'\.json$'), '');
    if (prev.isNotEmpty) {
      last = prev;
    }
  }
  return last.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
}

class PythonEmitter {
  final AnalysedCatalog catalog;
  final String baseImport;
  final String catalogName;

  PythonEmitter(this.catalog, {String? baseImport, String? catalogName})
    : baseImport = baseImport ?? 'a2ui.builder.base',
      catalogName = catalogName ?? extractCatalogName(catalog.catalogId);

  String generate() {
    final lines = <String>[
      licenseHeader.trim(),
      '',
      '# ==============================================================================',
      '# CODE GENERATED BY @a2ui/cli. DO NOT EDIT DIRECTLY.',
      '#',
      '# Catalog ID: ${catalog.catalogId}',
      '#',
      '# This file was automatically generated by the A2UI CLI code generator.',
      '# Any manual modifications will be lost upon regeneration.',
      '# ==============================================================================',
      '"""Type-safe A2UI builders for $catalogName (version ${catalog.specVersion}).',
      '',
      'AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.',
      'Generated by @a2ui/cli.',
      '"""',
      '',
      '__a2ui_codegen__ = "@a2ui/cli"',
      '',
      'from typing import Any, Mapping, Literal, Optional, Sequence, Union',
      '',
      'from $baseImport import (',
      '    Action,',
      '    CheckRule,',
      '    ComponentBuilderNode,',
      '    ComponentRef,',
      '    ComponentTree,',
      '    DataBinding,',
      '    DynamicChildList,',
      '    ExternalComponentBuilderNode,',
      '    FunctionCall,',
      '    IdAllocator,',
      '    Slot,',
      '    SlotList,',
      '    bind,',
      '    create_surface,',
      '    flatten_component_tree,',
      '    update_components,',
      ')',
      '',
      '',
      'def _serialize_prop(val: Any) -> Any:',
      '    if hasattr(val, "to_dict"):',
      '        return val.to_dict()',
      '    if isinstance(val, (list, tuple)):',
      '        return [_serialize_prop(item) for item in val]',
      '    if isinstance(val, dict):',
      '        return {k: _serialize_prop(v) for k, v in val.items()}',
      '    return val',
      '',
      '',
      '# =============================================================================',
      '# Types & Enums',
      '# =============================================================================',
      '',
    ];

    for (final entry in catalog.enums.entries) {
      final vals = entry.value.values.map((v) => '"$v"').join(', ');
      lines.add('${entry.key} = Literal[$vals] | str');
    }
    lines.add('');
    lines.add('');

    lines.add(
      '# =============================================================================',
    );
    lines.add('# Components');
    lines.add(
      '# =============================================================================',
    );
    lines.add('');

    for (final comp in catalog.components.values) {
      lines.add(_generateComponentClass(comp));
      lines.add('');
    }

    if (catalog.functions.isNotEmpty) {
      lines.add(
        '# =============================================================================',
      );
      lines.add('# Functions');
      lines.add(
        '# =============================================================================',
      );
      lines.add('');
      for (final fn in catalog.functions.values) {
        lines.add(_generateFunctionDef(fn));
        lines.add('');
      }
    }

    lines.add(
      '# =============================================================================',
    );
    lines.add('# Exports');
    lines.add(
      '# =============================================================================',
    );
    lines.add('');

    final allExports = [
      ...catalog.enums.keys,
      ...catalog.components.keys,
      ...catalog.functions.keys.map((f) => toSnakeCase(f)),
      'Action',
      'CheckRule',
      'ComponentBuilderNode',
      'ComponentRef',
      'ComponentTree',
      'DataBinding',
      'DynamicChildList',
      'ExternalComponentBuilderNode',
      'FunctionCall',
      'IdAllocator',
      'Slot',
      'SlotList',
      'bind',
      'create_surface',
      'flatten_component_tree',
      'update_components',
    ].map((e) => '"$e"').toList();

    lines.add('__all__ = [${allExports.join(', ')}]');
    lines.add('');

    return lines.join('\n');
  }

  List<String> emit(String targetPath) {
    String filePath;
    if (targetPath.endsWith('.py')) {
      filePath = targetPath;
      final parentDir = Directory(p.dirname(filePath));
      if (!parentDir.existsSync()) {
        parentDir.createSync(recursive: true);
      }
    } else {
      final outDir = Directory(targetPath);
      if (!outDir.existsSync()) {
        outDir.createSync(recursive: true);
      }
      filePath = p.join(targetPath, '$catalogName.py');
    }

    File(filePath).writeAsStringSync(generate());
    return [filePath];
  }

  String _generateComponentClass(AnalysedComponentApi comp) {
    final lines = <String>['class ${comp.name}(ComponentBuilderNode):'];
    final doc = comp.description ?? '${comp.name} component.';
    lines.add('    r"""$doc"""');
    lines.add('');
    lines.add('    component: Literal["${comp.name}"] = "${comp.name}"');

    for (final entry in comp.properties.entries) {
      final pName = entry.key;
      final prop = entry.value;
      if (pName == 'component') continue;
      final pyName = sanitizeIdent(pName);
      final pyType = typeToPython(prop.type);

      if (prop.isRequired) {
        lines.add('    $pyName: $pyType');
      } else {
        String defaultStr = 'None';
        if (prop.defaultValue != null) {
          if (prop.defaultValue is String) {
            defaultStr = '"${prop.defaultValue}"';
          } else if (prop.defaultValue is bool) {
            defaultStr = prop.defaultValue == true ? 'True' : 'False';
          } else if (prop.defaultValue is num) {
            defaultStr = prop.defaultValue.toString();
          }
        }
        lines.add('    $pyName: Optional[$pyType] = $defaultStr');
      }
    }

    lines.add('');
    lines.add('    def to_dict(self) -> dict[str, Any]:');
    lines.add('        d: dict[str, Any] = {"component": self.component}');
    for (final pName in comp.properties.keys) {
      if (pName == 'component' || pName == 'id') continue;
      final pyName = sanitizeIdent(pName);
      lines.add('        if self.$pyName is not None:');
      lines.add('            d["$pName"] = _serialize_prop(self.$pyName)');
    }
    lines.add('        if self.id is not None:');
    lines.add('            d["id"] = self.id');
    lines.add('        return d');

    return lines.join('\n');
  }

  String _generateFunctionDef(AnalysedFunctionApi fn) {
    final paramSigs = <String>['*'];
    final argsDictItems = <String>[];
    final pyFnName = toSnakeCase(fn.name);

    for (final entry in fn.parameters.entries) {
      final pName = entry.key;
      final pDesc = entry.value;
      final pyParam = sanitizeIdent(pName);
      final pyType = typeToPython(pDesc.type);
      if (pDesc.isRequired) {
        paramSigs.add('$pyParam: $pyType');
      } else {
        paramSigs.add('$pyParam: Optional[$pyType] = None');
      }
      argsDictItems.add(
        '    if $pyParam is not None:\n        args["$pName"] = $pyParam.to_dict() if hasattr($pyParam, "to_dict") else $pyParam',
      );
    }

    paramSigs.add('call_id: Optional[str] = None');
    final paramsStr = paramSigs.join(', ');

    final doc = fn.description ?? 'Invokes catalog function ${fn.name}.';
    final lines = <String>[
      'def $pyFnName($paramsStr) -> FunctionCall:',
      '    r"""$doc"""',
      '    args: dict[str, Any] = {}',
    ];
    if (argsDictItems.isNotEmpty) {
      lines.add(argsDictItems.join('\n'));
    }
    lines.add(
      '    return FunctionCall(call="${fn.name}", args=args, call_id=call_id)',
    );

    return lines.join('\n');
  }
}
