# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ==============================================================================
# CODE GENERATED BY @a2ui/cli. DO NOT EDIT DIRECTLY.
#
# Catalog ID: https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json
#
# This file was automatically generated by the A2UI CLI code generator.
# Any manual modifications will be lost upon regeneration.
# ==============================================================================
"""Type-safe A2UI builders for basic (version v0.9.1).

AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
Generated by @a2ui/cli.
"""

__a2ui_codegen__ = "@a2ui/cli"

from typing import Any, Mapping, Literal, Optional, Sequence, Union

from a2ui.builder.base import (
    Action,
    CheckRule,
    ComponentBuilderNode,
    ComponentRef,
    ComponentTree,
    DataBinding,
    DynamicChildList,
    ExternalComponentBuilderNode,
    FunctionCall,
    IdAllocator,
    Slot,
    SlotList,
    bind,
    create_surface,
    flatten_component_tree,
    update_components,
)


# =============================================================================
# Types & Enums
# =============================================================================

TextVariant = Literal["h1", "h2", "h3", "h4", "h5", "caption", "body"]
ImageFit = Literal["contain", "cover", "fill", "none", "scaleDown"]
ImageVariant = Literal[
    "icon", "avatar", "smallFeature", "mediumFeature", "largeFeature", "header"
]
IconName = Literal[
    "accountCircle",
    "add",
    "arrowBack",
    "arrowForward",
    "attachFile",
    "calendarToday",
    "call",
    "camera",
    "check",
    "close",
    "delete",
    "download",
    "edit",
    "event",
    "error",
    "fastForward",
    "favorite",
    "favoriteOff",
    "folder",
    "help",
    "home",
    "info",
    "locationOn",
    "lock",
    "lockOpen",
    "mail",
    "menu",
    "moreVert",
    "moreHoriz",
    "notificationsOff",
    "notifications",
    "pause",
    "payment",
    "person",
    "phone",
    "photo",
    "play",
    "print",
    "refresh",
    "rewind",
    "search",
    "send",
    "settings",
    "share",
    "shoppingCart",
    "skipNext",
    "skipPrevious",
    "star",
    "starHalf",
    "starOff",
    "stop",
    "upload",
    "visibility",
    "visibilityOff",
    "volumeDown",
    "volumeMute",
    "volumeOff",
    "volumeUp",
    "warning",
]
FlexJustify = Literal[
    "start",
    "center",
    "end",
    "spaceBetween",
    "spaceAround",
    "spaceEvenly",
    "stretch",
]
FlexAlign = Literal["center", "end", "start", "stretch"]
ListDirection = Literal["vertical", "horizontal"]
ListAlign = Literal["start", "center", "end", "stretch"]
DividerAxis = Literal["horizontal", "vertical"]
ButtonVariant = Literal["default", "primary", "borderless"]
TextFieldVariant = Literal["longText", "number", "shortText", "obscured"]
ChoicePickerVariant = Literal["multipleSelection", "mutuallyExclusive"]
ChoicePickerDisplayStyle = Literal["checkbox", "chips"]


# =============================================================================
# Components
# =============================================================================


class Text(ComponentBuilderNode):
    r"""Text component."""

    component: Literal["Text"] = "Text"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    text: str | DataBinding | FunctionCall
    variant: Optional[TextVariant] = "body"


class Image(ComponentBuilderNode):
    r"""Image component."""

    component: Literal["Image"] = "Image"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None
    fit: Optional[ImageFit] = "fill"
    variant: Optional[ImageVariant] = "mediumFeature"


class Icon(ComponentBuilderNode):
    r"""Icon component."""

    component: Literal["Icon"] = "Icon"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    name: IconName


class Video(ComponentBuilderNode):
    r"""Video component."""

    component: Literal["Video"] = "Video"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall


class AudioPlayer(ComponentBuilderNode):
    r"""AudioPlayer component."""

    component: Literal["AudioPlayer"] = "AudioPlayer"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None


class Row(ComponentBuilderNode):
    r"""Row component."""

    component: Literal["Row"] = "Row"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: SlotList | DynamicChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"


class Column(ComponentBuilderNode):
    r"""Column component."""

    component: Literal["Column"] = "Column"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: SlotList | DynamicChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"


class List(ComponentBuilderNode):
    r"""List component."""

    component: Literal["List"] = "List"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: SlotList | DynamicChildList
    direction: Optional[ListDirection] = "vertical"
    align: Optional[ListAlign] = "stretch"


class Card(ComponentBuilderNode):
    r"""Card component."""

    component: Literal["Card"] = "Card"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    child: Slot


class Tabs(ComponentBuilderNode):
    r"""Tabs component."""

    component: Literal["Tabs"] = "Tabs"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    tabs: Sequence[Mapping[str, Any]]


class Modal(ComponentBuilderNode):
    r"""Modal component."""

    component: Literal["Modal"] = "Modal"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    trigger: Slot
    content: Slot


class Divider(ComponentBuilderNode):
    r"""Divider component."""

    component: Literal["Divider"] = "Divider"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    axis: Optional[DividerAxis] = "horizontal"


class Button(ComponentBuilderNode):
    r"""Button component."""

    component: Literal["Button"] = "Button"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    child: Slot
    variant: Optional[ButtonVariant] = "default"
    action: Action


class TextField(ComponentBuilderNode):
    r"""TextField component."""

    component: Literal["TextField"] = "TextField"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: str | DataBinding | FunctionCall
    value: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[TextFieldVariant] = "shortText"
    validationRegexp: Optional[str] = None


class CheckBox(ComponentBuilderNode):
    r"""CheckBox component."""

    component: Literal["CheckBox"] = "CheckBox"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: str | DataBinding | FunctionCall
    value: bool | DataBinding | FunctionCall


class ChoicePicker(ComponentBuilderNode):
    r"""ChoicePicker component."""

    component: Literal["ChoicePicker"] = "ChoicePicker"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[ChoicePickerVariant] = "mutuallyExclusive"
    options: Sequence[Mapping[str, Any]]
    value: Sequence[str] | DataBinding | FunctionCall
    displayStyle: Optional[ChoicePickerDisplayStyle] = "checkbox"
    filterable: Optional[bool] = False


class Slider(ComponentBuilderNode):
    r"""Slider component."""

    component: Literal["Slider"] = "Slider"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    min: Optional[float] = 0
    max: float
    value: float | DataBinding | FunctionCall


class DateTimeInput(ComponentBuilderNode):
    r"""DateTimeInput component."""

    component: Literal["DateTimeInput"] = "DateTimeInput"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    value: str | DataBinding | FunctionCall
    enableDate: Optional[bool] = False
    enableTime: Optional[bool] = False
    min: Optional[Any] = None
    max: Optional[Any] = None
    label: Optional[str | DataBinding | FunctionCall] = None


# =============================================================================
# Functions
# =============================================================================


def required(*, value: Any, call_id: Optional[str] = None) -> FunctionCall:
    r"""Invokes catalog function required."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    return FunctionCall(call="required", args=args, call_id=call_id)


def regex(
    *,
    value: str | DataBinding | FunctionCall,
    pattern: str,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function regex."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    if pattern is not None:
        args["pattern"] = pattern
    return FunctionCall(call="regex", args=args, call_id=call_id)


def length(
    *,
    value: str | DataBinding | FunctionCall,
    min: Optional[float] = None,
    max: Optional[float] = None,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function length."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    if min is not None:
        args["min"] = min
    if max is not None:
        args["max"] = max
    return FunctionCall(call="length", args=args, call_id=call_id)


def numeric(
    *,
    value: float | DataBinding | FunctionCall,
    min: Optional[float] = None,
    max: Optional[float] = None,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function numeric."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    if min is not None:
        args["min"] = min
    if max is not None:
        args["max"] = max
    return FunctionCall(call="numeric", args=args, call_id=call_id)


def email(
    *, value: str | DataBinding | FunctionCall, call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function email."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    return FunctionCall(call="email", args=args, call_id=call_id)


def format_string(
    *, value: str | DataBinding | FunctionCall, call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function formatString."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    return FunctionCall(call="formatString", args=args, call_id=call_id)


def format_number(
    *,
    value: float | DataBinding | FunctionCall,
    decimals: Optional[float | DataBinding | FunctionCall] = None,
    grouping: Optional[bool | DataBinding | FunctionCall] = None,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function formatNumber."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    if decimals is not None:
        args["decimals"] = decimals
    if grouping is not None:
        args["grouping"] = grouping
    return FunctionCall(call="formatNumber", args=args, call_id=call_id)


def format_currency(
    *,
    value: float | DataBinding | FunctionCall,
    currency: str | DataBinding | FunctionCall,
    decimals: Optional[float | DataBinding | FunctionCall] = None,
    grouping: Optional[bool | DataBinding | FunctionCall] = None,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function formatCurrency."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    if currency is not None:
        args["currency"] = currency
    if decimals is not None:
        args["decimals"] = decimals
    if grouping is not None:
        args["grouping"] = grouping
    return FunctionCall(call="formatCurrency", args=args, call_id=call_id)


def format_date(
    *,
    value: Any | DataBinding | FunctionCall,
    format: str | DataBinding | FunctionCall,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function formatDate."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    if format is not None:
        args["format"] = format
    return FunctionCall(call="formatDate", args=args, call_id=call_id)


def pluralize(
    *,
    value: float | DataBinding | FunctionCall,
    zero: Optional[str | DataBinding | FunctionCall] = None,
    one: Optional[str | DataBinding | FunctionCall] = None,
    two: Optional[str | DataBinding | FunctionCall] = None,
    few: Optional[str | DataBinding | FunctionCall] = None,
    many: Optional[str | DataBinding | FunctionCall] = None,
    other: str | DataBinding | FunctionCall,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function pluralize."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    if zero is not None:
        args["zero"] = zero
    if one is not None:
        args["one"] = one
    if two is not None:
        args["two"] = two
    if few is not None:
        args["few"] = few
    if many is not None:
        args["many"] = many
    if other is not None:
        args["other"] = other
    return FunctionCall(call="pluralize", args=args, call_id=call_id)


def open_url(*, url: str, call_id: Optional[str] = None) -> FunctionCall:
    r"""Invokes catalog function openUrl."""
    args: dict[str, Any] = {}
    if url is not None:
        args["url"] = url
    return FunctionCall(call="openUrl", args=args, call_id=call_id)


def and_(
    *,
    values: Sequence[bool | DataBinding | FunctionCall],
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function and."""
    args: dict[str, Any] = {}
    if values is not None:
        args["values"] = values
    return FunctionCall(call="and", args=args, call_id=call_id)


def or_(
    *,
    values: Sequence[bool | DataBinding | FunctionCall],
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function or."""
    args: dict[str, Any] = {}
    if values is not None:
        args["values"] = values
    return FunctionCall(call="or", args=args, call_id=call_id)


def not_(
    *, value: bool | DataBinding | FunctionCall, call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function not."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value
    return FunctionCall(call="not", args=args, call_id=call_id)


# =============================================================================
# Exports
# =============================================================================

__all__ = [
    "TextVariant",
    "ImageFit",
    "ImageVariant",
    "IconName",
    "FlexJustify",
    "FlexAlign",
    "ListDirection",
    "ListAlign",
    "DividerAxis",
    "ButtonVariant",
    "TextFieldVariant",
    "ChoicePickerVariant",
    "ChoicePickerDisplayStyle",
    "Text",
    "Image",
    "Icon",
    "Video",
    "AudioPlayer",
    "Row",
    "Column",
    "List",
    "Card",
    "Tabs",
    "Modal",
    "Divider",
    "Button",
    "TextField",
    "CheckBox",
    "ChoicePicker",
    "Slider",
    "DateTimeInput",
    "required",
    "regex",
    "length",
    "numeric",
    "email",
    "format_string",
    "format_number",
    "format_currency",
    "format_date",
    "pluralize",
    "open_url",
    "and_",
    "or_",
    "not_",
    "Action",
    "CheckRule",
    "ComponentBuilderNode",
    "ComponentRef",
    "ComponentTree",
    "DataBinding",
    "DynamicChildList",
    "ExternalComponentBuilderNode",
    "FunctionCall",
    "IdAllocator",
    "Slot",
    "SlotList",
    "bind",
    "create_surface",
    "flatten_component_tree",
    "update_components",
]
