# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ==============================================================================
# CODE GENERATED BY @a2ui/cli. DO NOT EDIT DIRECTLY.
#
# Catalog ID: https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json
#
# This file was automatically generated by the A2UI CLI code generator.
# Any manual modifications will be lost upon regeneration.
# ==============================================================================
"""Type-safe A2UI builders for basic (version v0.9.1).

AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
Generated by @a2ui/cli.
"""

__a2ui_codegen__ = "@a2ui/cli"

from typing import Any, Mapping, Literal, Optional, Sequence, Union

from a2ui.builder.base import (
    Action,
    CheckRule,
    ComponentBuilderNode,
    ComponentRef,
    ComponentTree,
    DataBinding,
    DynamicChildList,
    ExternalComponentBuilderNode,
    FunctionCall,
    IdAllocator,
    Slot,
    SlotList,
    bind,
    create_surface,
    flatten_component_tree,
    update_components,
)


def _serialize_prop(val: Any) -> Any:
    if hasattr(val, "to_dict"):
        return val.to_dict()
    if isinstance(val, (list, tuple)):
        return [_serialize_prop(item) for item in val]
    if isinstance(val, dict):
        return {k: _serialize_prop(v) for k, v in val.items()}
    return val


# =============================================================================
# Types & Enums
# =============================================================================

TextVariant = Literal["h1", "h2", "h3", "h4", "h5", "caption", "body"] | str
ImageFit = Literal["contain", "cover", "fill", "none", "scaleDown"] | str
ImageVariant = (
    Literal["icon", "avatar", "smallFeature", "mediumFeature", "largeFeature", "header"]
    | str
)
IconName = (
    Literal[
        "accountCircle",
        "add",
        "arrowBack",
        "arrowForward",
        "attachFile",
        "calendarToday",
        "call",
        "camera",
        "check",
        "close",
        "delete",
        "download",
        "edit",
        "event",
        "error",
        "fastForward",
        "favorite",
        "favoriteOff",
        "folder",
        "help",
        "home",
        "info",
        "locationOn",
        "lock",
        "lockOpen",
        "mail",
        "menu",
        "moreVert",
        "moreHoriz",
        "notificationsOff",
        "notifications",
        "pause",
        "payment",
        "person",
        "phone",
        "photo",
        "play",
        "print",
        "refresh",
        "rewind",
        "search",
        "send",
        "settings",
        "share",
        "shoppingCart",
        "skipNext",
        "skipPrevious",
        "star",
        "starHalf",
        "starOff",
        "stop",
        "upload",
        "visibility",
        "visibilityOff",
        "volumeDown",
        "volumeMute",
        "volumeOff",
        "volumeUp",
        "warning",
    ]
    | str
)
FlexJustify = (
    Literal[
        "start",
        "center",
        "end",
        "spaceBetween",
        "spaceAround",
        "spaceEvenly",
        "stretch",
    ]
    | str
)
FlexAlign = Literal["center", "end", "start", "stretch"] | str
ListDirection = Literal["vertical", "horizontal"] | str
ListAlign = Literal["start", "center", "end", "stretch"] | str
DividerAxis = Literal["horizontal", "vertical"] | str
ButtonVariant = Literal["default", "primary", "borderless"] | str
TextFieldVariant = Literal["longText", "number", "shortText", "obscured"] | str
ChoicePickerVariant = Literal["multipleSelection", "mutuallyExclusive"] | str
ChoicePickerDisplayStyle = Literal["checkbox", "chips"] | str


# =============================================================================
# Components
# =============================================================================


class Text(ComponentBuilderNode):
    r"""Text component."""

    component: Literal["Text"] = "Text"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    text: str | DataBinding | FunctionCall
    variant: Optional[TextVariant] = "body"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.text is not None:
            d["text"] = _serialize_prop(self.text)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.id is not None:
            d["id"] = self.id
        return d


class Image(ComponentBuilderNode):
    r"""Image component."""

    component: Literal["Image"] = "Image"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None
    fit: Optional[ImageFit] = "fill"
    variant: Optional[ImageVariant] = "mediumFeature"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.url is not None:
            d["url"] = _serialize_prop(self.url)
        if self.description is not None:
            d["description"] = _serialize_prop(self.description)
        if self.fit is not None:
            d["fit"] = _serialize_prop(self.fit)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.id is not None:
            d["id"] = self.id
        return d


class Icon(ComponentBuilderNode):
    r"""Icon component."""

    component: Literal["Icon"] = "Icon"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    name: IconName

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.name is not None:
            d["name"] = _serialize_prop(self.name)
        if self.id is not None:
            d["id"] = self.id
        return d


class Video(ComponentBuilderNode):
    r"""Video component."""

    component: Literal["Video"] = "Video"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.url is not None:
            d["url"] = _serialize_prop(self.url)
        if self.id is not None:
            d["id"] = self.id
        return d


class AudioPlayer(ComponentBuilderNode):
    r"""AudioPlayer component."""

    component: Literal["AudioPlayer"] = "AudioPlayer"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.url is not None:
            d["url"] = _serialize_prop(self.url)
        if self.description is not None:
            d["description"] = _serialize_prop(self.description)
        if self.id is not None:
            d["id"] = self.id
        return d


class Row(ComponentBuilderNode):
    r"""Row component."""

    component: Literal["Row"] = "Row"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: SlotList | DynamicChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.children is not None:
            d["children"] = _serialize_prop(self.children)
        if self.justify is not None:
            d["justify"] = _serialize_prop(self.justify)
        if self.align is not None:
            d["align"] = _serialize_prop(self.align)
        if self.id is not None:
            d["id"] = self.id
        return d


class Column(ComponentBuilderNode):
    r"""Column component."""

    component: Literal["Column"] = "Column"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: SlotList | DynamicChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.children is not None:
            d["children"] = _serialize_prop(self.children)
        if self.justify is not None:
            d["justify"] = _serialize_prop(self.justify)
        if self.align is not None:
            d["align"] = _serialize_prop(self.align)
        if self.id is not None:
            d["id"] = self.id
        return d


class List(ComponentBuilderNode):
    r"""List component."""

    component: Literal["List"] = "List"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: SlotList | DynamicChildList
    direction: Optional[ListDirection] = "vertical"
    align: Optional[ListAlign] = "stretch"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.children is not None:
            d["children"] = _serialize_prop(self.children)
        if self.direction is not None:
            d["direction"] = _serialize_prop(self.direction)
        if self.align is not None:
            d["align"] = _serialize_prop(self.align)
        if self.id is not None:
            d["id"] = self.id
        return d


class Card(ComponentBuilderNode):
    r"""Card component."""

    component: Literal["Card"] = "Card"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    child: Slot

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.child is not None:
            d["child"] = _serialize_prop(self.child)
        if self.id is not None:
            d["id"] = self.id
        return d


class Tabs(ComponentBuilderNode):
    r"""Tabs component."""

    component: Literal["Tabs"] = "Tabs"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    tabs: Sequence[Mapping[str, Any]]

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.tabs is not None:
            d["tabs"] = _serialize_prop(self.tabs)
        if self.id is not None:
            d["id"] = self.id
        return d


class Modal(ComponentBuilderNode):
    r"""Modal component."""

    component: Literal["Modal"] = "Modal"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    trigger: Slot
    content: Slot

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.trigger is not None:
            d["trigger"] = _serialize_prop(self.trigger)
        if self.content is not None:
            d["content"] = _serialize_prop(self.content)
        if self.id is not None:
            d["id"] = self.id
        return d


class Divider(ComponentBuilderNode):
    r"""Divider component."""

    component: Literal["Divider"] = "Divider"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    axis: Optional[DividerAxis] = "horizontal"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.axis is not None:
            d["axis"] = _serialize_prop(self.axis)
        if self.id is not None:
            d["id"] = self.id
        return d


class Button(ComponentBuilderNode):
    r"""Button component."""

    component: Literal["Button"] = "Button"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    child: Slot
    variant: Optional[ButtonVariant] = "default"
    action: Action

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.child is not None:
            d["child"] = _serialize_prop(self.child)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.action is not None:
            d["action"] = _serialize_prop(self.action)
        if self.id is not None:
            d["id"] = self.id
        return d


class TextField(ComponentBuilderNode):
    r"""TextField component."""

    component: Literal["TextField"] = "TextField"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: str | DataBinding | FunctionCall
    value: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[TextFieldVariant] = "shortText"
    validationRegexp: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.validationRegexp is not None:
            d["validationRegexp"] = _serialize_prop(self.validationRegexp)
        if self.id is not None:
            d["id"] = self.id
        return d


class CheckBox(ComponentBuilderNode):
    r"""CheckBox component."""

    component: Literal["CheckBox"] = "CheckBox"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: str | DataBinding | FunctionCall
    value: bool | DataBinding | FunctionCall

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.id is not None:
            d["id"] = self.id
        return d


class ChoicePicker(ComponentBuilderNode):
    r"""ChoicePicker component."""

    component: Literal["ChoicePicker"] = "ChoicePicker"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[ChoicePickerVariant] = "mutuallyExclusive"
    options: Sequence[Mapping[str, Any]]
    value: Sequence[str] | DataBinding | FunctionCall
    displayStyle: Optional[ChoicePickerDisplayStyle] = "checkbox"
    filterable: Optional[bool] = False

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.options is not None:
            d["options"] = _serialize_prop(self.options)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.displayStyle is not None:
            d["displayStyle"] = _serialize_prop(self.displayStyle)
        if self.filterable is not None:
            d["filterable"] = _serialize_prop(self.filterable)
        if self.id is not None:
            d["id"] = self.id
        return d


class Slider(ComponentBuilderNode):
    r"""Slider component."""

    component: Literal["Slider"] = "Slider"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    min: Optional[float] = 0
    max: float
    value: float | DataBinding | FunctionCall

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.min is not None:
            d["min"] = _serialize_prop(self.min)
        if self.max is not None:
            d["max"] = _serialize_prop(self.max)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.id is not None:
            d["id"] = self.id
        return d


class DateTimeInput(ComponentBuilderNode):
    r"""DateTimeInput component."""

    component: Literal["DateTimeInput"] = "DateTimeInput"
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    value: str | DataBinding | FunctionCall
    enableDate: Optional[bool] = False
    enableTime: Optional[bool] = False
    min: Optional[Any] = None
    max: Optional[Any] = None
    label: Optional[str | DataBinding | FunctionCall] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.enableDate is not None:
            d["enableDate"] = _serialize_prop(self.enableDate)
        if self.enableTime is not None:
            d["enableTime"] = _serialize_prop(self.enableTime)
        if self.min is not None:
            d["min"] = _serialize_prop(self.min)
        if self.max is not None:
            d["max"] = _serialize_prop(self.max)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.id is not None:
            d["id"] = self.id
        return d


# =============================================================================
# Functions
# =============================================================================


def required(*, value: Any, call_id: Optional[str] = None) -> FunctionCall:
    r"""Invokes catalog function required."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    return FunctionCall(call="required", args=args, call_id=call_id)


def regex(
    *,
    value: str | DataBinding | FunctionCall,
    pattern: str,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function regex."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if pattern is not None:
        args["pattern"] = pattern.to_dict() if hasattr(pattern, "to_dict") else pattern
    return FunctionCall(call="regex", args=args, call_id=call_id)


def length(
    *,
    value: str | DataBinding | FunctionCall,
    min: Optional[float] = None,
    max: Optional[float] = None,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function length."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if min is not None:
        args["min"] = min.to_dict() if hasattr(min, "to_dict") else min
    if max is not None:
        args["max"] = max.to_dict() if hasattr(max, "to_dict") else max
    return FunctionCall(call="length", args=args, call_id=call_id)


def numeric(
    *,
    value: float | DataBinding | FunctionCall,
    min: Optional[float] = None,
    max: Optional[float] = None,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function numeric."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if min is not None:
        args["min"] = min.to_dict() if hasattr(min, "to_dict") else min
    if max is not None:
        args["max"] = max.to_dict() if hasattr(max, "to_dict") else max
    return FunctionCall(call="numeric", args=args, call_id=call_id)


def email(
    *, value: str | DataBinding | FunctionCall, call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function email."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    return FunctionCall(call="email", args=args, call_id=call_id)


def format_string(
    *, value: str | DataBinding | FunctionCall, call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function formatString."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    return FunctionCall(call="formatString", args=args, call_id=call_id)


def format_number(
    *,
    value: float | DataBinding | FunctionCall,
    decimals: Optional[float | DataBinding | FunctionCall] = None,
    grouping: Optional[bool | DataBinding | FunctionCall] = None,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function formatNumber."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if decimals is not None:
        args["decimals"] = (
            decimals.to_dict() if hasattr(decimals, "to_dict") else decimals
        )
    if grouping is not None:
        args["grouping"] = (
            grouping.to_dict() if hasattr(grouping, "to_dict") else grouping
        )
    return FunctionCall(call="formatNumber", args=args, call_id=call_id)


def format_currency(
    *,
    value: float | DataBinding | FunctionCall,
    currency: str | DataBinding | FunctionCall,
    decimals: Optional[float | DataBinding | FunctionCall] = None,
    grouping: Optional[bool | DataBinding | FunctionCall] = None,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function formatCurrency."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if currency is not None:
        args["currency"] = (
            currency.to_dict() if hasattr(currency, "to_dict") else currency
        )
    if decimals is not None:
        args["decimals"] = (
            decimals.to_dict() if hasattr(decimals, "to_dict") else decimals
        )
    if grouping is not None:
        args["grouping"] = (
            grouping.to_dict() if hasattr(grouping, "to_dict") else grouping
        )
    return FunctionCall(call="formatCurrency", args=args, call_id=call_id)


def format_date(
    *,
    value: Any | DataBinding | FunctionCall,
    format: str | DataBinding | FunctionCall,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function formatDate."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if format is not None:
        args["format"] = format.to_dict() if hasattr(format, "to_dict") else format
    return FunctionCall(call="formatDate", args=args, call_id=call_id)


def pluralize(
    *,
    value: float | DataBinding | FunctionCall,
    zero: Optional[str | DataBinding | FunctionCall] = None,
    one: Optional[str | DataBinding | FunctionCall] = None,
    two: Optional[str | DataBinding | FunctionCall] = None,
    few: Optional[str | DataBinding | FunctionCall] = None,
    many: Optional[str | DataBinding | FunctionCall] = None,
    other: str | DataBinding | FunctionCall,
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function pluralize."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if zero is not None:
        args["zero"] = zero.to_dict() if hasattr(zero, "to_dict") else zero
    if one is not None:
        args["one"] = one.to_dict() if hasattr(one, "to_dict") else one
    if two is not None:
        args["two"] = two.to_dict() if hasattr(two, "to_dict") else two
    if few is not None:
        args["few"] = few.to_dict() if hasattr(few, "to_dict") else few
    if many is not None:
        args["many"] = many.to_dict() if hasattr(many, "to_dict") else many
    if other is not None:
        args["other"] = other.to_dict() if hasattr(other, "to_dict") else other
    return FunctionCall(call="pluralize", args=args, call_id=call_id)


def open_url(*, url: str, call_id: Optional[str] = None) -> FunctionCall:
    r"""Invokes catalog function openUrl."""
    args: dict[str, Any] = {}
    if url is not None:
        args["url"] = url.to_dict() if hasattr(url, "to_dict") else url
    return FunctionCall(call="openUrl", args=args, call_id=call_id)


def and_(
    *,
    values: Sequence[bool | DataBinding | FunctionCall],
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function and."""
    args: dict[str, Any] = {}
    if values is not None:
        args["values"] = values.to_dict() if hasattr(values, "to_dict") else values
    return FunctionCall(call="and", args=args, call_id=call_id)


def or_(
    *,
    values: Sequence[bool | DataBinding | FunctionCall],
    call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function or."""
    args: dict[str, Any] = {}
    if values is not None:
        args["values"] = values.to_dict() if hasattr(values, "to_dict") else values
    return FunctionCall(call="or", args=args, call_id=call_id)


def not_(
    *, value: bool | DataBinding | FunctionCall, call_id: Optional[str] = None
) -> FunctionCall:
    r"""Invokes catalog function not."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    return FunctionCall(call="not", args=args, call_id=call_id)


# =============================================================================
# Exports
# =============================================================================

__all__ = [
    "TextVariant",
    "ImageFit",
    "ImageVariant",
    "IconName",
    "FlexJustify",
    "FlexAlign",
    "ListDirection",
    "ListAlign",
    "DividerAxis",
    "ButtonVariant",
    "TextFieldVariant",
    "ChoicePickerVariant",
    "ChoicePickerDisplayStyle",
    "Text",
    "Image",
    "Icon",
    "Video",
    "AudioPlayer",
    "Row",
    "Column",
    "List",
    "Card",
    "Tabs",
    "Modal",
    "Divider",
    "Button",
    "TextField",
    "CheckBox",
    "ChoicePicker",
    "Slider",
    "DateTimeInput",
    "required",
    "regex",
    "length",
    "numeric",
    "email",
    "format_string",
    "format_number",
    "format_currency",
    "format_date",
    "pluralize",
    "open_url",
    "and_",
    "or_",
    "not_",
    "Action",
    "CheckRule",
    "ComponentBuilderNode",
    "ComponentRef",
    "ComponentTree",
    "DataBinding",
    "DynamicChildList",
    "ExternalComponentBuilderNode",
    "FunctionCall",
    "IdAllocator",
    "Slot",
    "SlotList",
    "bind",
    "create_surface",
    "flatten_component_tree",
    "update_components",
]
